project_id = "caferest"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[mailer]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "100MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[realtime]
enabled = true
