import type { LucideIcon } from "lucide-react";
import {
  Apple,
  CupSoda,
  CookingPot,
  Sandwich,
  Coffee,
  Soup,
  Salad,
  IceCream,
  Cake,
  Beer,
  Wine,
  Martini,
  Croissant,
  Pizza,
  Hamburger,
  Utensils,
  Egg,
  Fish,
  Drumstick,
  Milk,
  Leaf,
  Flame,
  Sparkles,
  Tag,
  ChefHat,
  Cookie,
  Donut,
  GlassWater,
  Lollipop,
  Popcorn,
  Citrus,
  Carrot,
  Banana,
  Grape,
  Dessert,
  Container,
  Blend,
  Star,
  Heart,
  Zap,
  Sun,
  Moon,
  Snowflake,
  Anchor,
  Gift,
  Globe,
  Home,
  Landmark,
  Layers,
  MapPin,
  Palette,
  PartyPopper,
  PiggyBank,
  Rocket,
  School,
  Shield,
  ShoppingBag,
  Trophy,
  Boxes,
} from "lucide-react";

/**
 * Stable icon registry. Categories store a kebab-case icon *name* (never the
 * component) so the value is JSON-safe and survives renames. Unknown names
 * fall back to `Tag` instead of crashing the render.
 */
export const CATEGORY_ICON_NAMES = [
  "cup-soda",
  "coffee",
  "soup",
  "glass-water",
  "beer",
  "wine",
  "martini",
  "milk",
  "salad",
  "apple",
  "citrus",
  "banana",
  "carrot",
  "grape",
  "drumstick",
  "fish",
  "egg",
  "cooking-pot",
  "sandwich",
  "croissant",
  "pizza",
  "hamburger",
  "cookie",
  "donut",
  "cake",
  "ice-cream",
  "dessert",
  "lollipop",
  "popcorn",
  "chef-hat",
  "utensils",
  "container",
  "blend",
  "flame",
  "leaf",
  "sparkles",
  "star",
  "heart",
  "zap",
  "sun",
  "moon",
  "snowflake",
  "anchor",
  "gift",
  "globe",
  "home",
  "landmark",
  "layers",
  "map-pin",
  "palette",
  "party-popper",
  "piggy-bank",
  "rocket",
  "school",
  "shield",
  "shopping-bag",
  "trophy",
  "boxes",
  "tag",
] as const;

const ICON_REGISTRY: Record<string, LucideIcon> = {
  "cup-soda": CupSoda,
  coffee: Coffee,
  soup: Soup,
  "glass-water": GlassWater,
  beer: Beer,
  wine: Wine,
  martini: Martini,
  milk: Milk,
  salad: Salad,
  apple: Apple,
  citrus: Citrus,
  banana: Banana,
  carrot: Carrot,
  grape: Grape,
  drumstick: Drumstick,
  fish: Fish,
  egg: Egg,
  "cooking-pot": CookingPot,
  sandwich: Sandwich,
  croissant: Croissant,
  pizza: Pizza,
  hamburger: Hamburger,
  cookie: Cookie,
  donut: Donut,
  cake: Cake,
  "ice-cream": IceCream,
  dessert: Dessert,
  lollipop: Lollipop,
  popcorn: Popcorn,
  "chef-hat": ChefHat,
  utensils: Utensils,
  container: Container,
  blend: Blend,
  flame: Flame,
  leaf: Leaf,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  snowflake: Snowflake,
  anchor: Anchor,
  gift: Gift,
  globe: Globe,
  home: Home,
  landmark: Landmark,
  layers: Layers,
  "map-pin": MapPin,
  palette: Palette,
  "party-popper": PartyPopper,
  "piggy-bank": PiggyBank,
  rocket: Rocket,
  school: School,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  trophy: Trophy,
  boxes: Boxes,
  tag: Tag,
};

/** Resolve a stored icon name to its Lucide component (safe fallback: Tag). */
export function getCategoryIcon(name: string | null): LucideIcon {
  if (!name) return Tag;
  return ICON_REGISTRY[name] ?? Tag;
}